name: Python Flake8 Lint

on:
  push:
    branches:
      - main
      - feature/*
jobs:
  flake8:
    name: Lint with flake8
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8" # 프로젝트에 맞는 Python 버전으로 설정

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        run: flake8 ./
        working-directory: ./aws_infra/lambda_file
